Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-12, with the labels that each got.

#364 Indicate support for Java 21 in README.md
  README.md
Labels: documentation

#361 Jpa cache properties recipe
  src/main/java/org/openrewrite/java/migrate/JpaCacheProperties.java
  src/main/resources/META-INF/rewrite/java-ee-7.yml
  src/test/java/org/openrewrite/java/migrate/JpaCachePropertiesTest.java
Labels: recipe

#366 CastArraysAsListToList Recipe
  src/main/java/org/openrewrite/java/migrate/CastArraysAsListToList.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/CastArraysAsListToListTest.java
Labels: recipe

#371 Fix #368/#370: Jakarta Faces 4 Support
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/jakarta-faces-4.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JakartaFacesXhtmlTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxFacesConfigXmlToJakartaFacesConfigXmlTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxFacesTagLibraryXmlToJakartaFacesTagLibraryXmlTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxWebFragmentXmlToJakartaWebFragmentXmlTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxWebXmlToJakartaWebXmlTest.java
Labels: recipe

#372 Fix #369: beans.xml EE10 migration
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxBeansXmlToJakartaBeansXmlTest.java
Labels: recipe

#374 Fix #373: Jakarta EE10 bean validation strings in Java
  src/main/java/org/openrewrite/java/migrate/jakarta/BeanValidationMessages.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/BeanValidationMessagesTest.java
Labels: recipe

#379 Escape slashes following change in rewrite-templating
  src/test/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtilsTest.java
  src/test/java/org/openrewrite/java/migrate/maven/shared/MavenSharedStringUtilsTest.java
  src/test/java/org/openrewrite/java/migrate/plexus/PlexusStringUtilsTest.java
Labels: bug

#378 Fix #377: EE10 Faces open source libraries
  src/main/resources/META-INF/rewrite/jakarta-faces-4.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/UpgradeFacesOpenSourceLibrariesTest.java
Labels: recipe

#380 CDI 4.0 beans.xml
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxBeansXmlToJakartaBeansXmlTest.java
Labels: bug

#382 Fix test failures after latest rewrite-templating changes
  .sdkmanrc
  src/test/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtilsTest.java
Labels: bug
