Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-11, with the labels that each got.

#312 Add new JDBC method implementations introduced in Java 6 and 7
  src/main/java/org/openrewrite/java/migrate/AddMissingMethodImplementation.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-6.yml
  src/main/resources/META-INF/rewrite/java-version-7.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava6Test.java
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava7Test.java
Labels: recipe

#339 Adopt SequencedCollection First and Last methods
  build.gradle.kts
  src/main/java/org/openrewrite/java/migrate/util/IteratorNext.java
  src/main/java/org/openrewrite/java/migrate/util/ListFirstAndLast.java
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/util/IteratorNextTest.java
  src/test/java/org/openrewrite/java/migrate/util/ListFirstAndLastTest.java
  src/test/java/org/openrewrite/java/migrate/util/SequencedCollectionTest.java
Labels: recipe, java 21+

#335 Adds MXbean recipe
  src/main/java/org/openrewrite/java/migrate/MXBeanNonPublic.java
  src/main/resources/META-INF/rewrite/java-version-8.yml
  src/test/java/org/openrewrite/java/migrate/MXBeanNonPublicTest.java
Labels: recipe

#347 BeanDiscovery recipe
  src/main/java/org/openrewrite/java/migrate/BeanDiscovery.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/BeanDiscoveryTest.java
Labels: recipe

#346 Recipes to migrate to Java EE 7, Java EE 8 & Jakarta EE 9
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/main/resources/META-INF/rewrite/java-ee-7.yml
  src/main/resources/META-INF/rewrite/java-ee-8.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateApacheWSSecurityPackagesTest.java
  src/test/java/org/openrewrite/java/migrate/javaee/ApacheDefaultProviderTest.java
  src/test/java/org/openrewrite/java/migrate/javaee/OpenJPAPersistenceProviderTest.java
  src/test/java/org/openrewrite/java/migrate/javaee/ServletIsRequestedSessionIdFromURLTest.java
  src/test/resources/META-INF/rewrite/classpath/javax.servlet-3.0.jar
  src/test/resources/META-INF/rewrite/classpath/wss4j-1.6.19.jar
  src/test/resources/META-INF/rewrite/classpath/wss4j-ws-security-common-2.0.0.jar
Labels: recipe

#350 Recipe FacesManagedBeansRemoved - Jakarta EE 10
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/FacesManagedBeansRemovedTest.java
  src/test/resources/META-INF/rewrite/classpath/cdi-api-2.0.SP1.jar
  src/test/resources/META-INF/rewrite/classpath/jakarta.enterprise.cdi-api-4.0.1.jar
  src/test/resources/META-INF/rewrite/classpath/jsf-api-2.1.29-11.jar
Labels: recipe

#348 ApplicationPath trailing slash and wildcard no longer supported on Jakarta EE
  src/main/java/org/openrewrite/java/migrate/jakarta/ApplicationPathWildcardNoLongerAccepted.java
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/ApplicationPathWildcardNoLongerAcceptedTest.java
  src/test/resources/META-INF/rewrite/classpath/jakarta.ws.rs-api-3.1.0.jar
Labels: recipe

#352 Replace URL constructors in Java 21
  src/main/java/org/openrewrite/java/migrate/net/URLConstructorsToURI.java
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/net/URLConstructorsToURITest.java
Labels: recipe, java 21+

#354 Hint at `Thread.stop()` throwing `UnsupportedOperationException`
  src/main/java/org/openrewrite/java/migrate/lang/ThreadStopUnsupported.java
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/lang/ThreadStopUnsupportedTest.java
Labels: recipe, java 21+

#247 Removing deprecated Runtime trace methods in move to Java 17
  src/main/java/org/openrewrite/java/migrate/lang/RemoveRuntimeTraceMethods.java
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/lang/RemoveDeprecatedRuntimeTest.java
Labels: recipe

#356 Consolidate Javax to Jakarta recipes
  src/main/resources/META-INF/rewrite/add-inject-dependencies.yml
  src/main/resources/META-INF/rewrite/jacoco.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/main/resources/META-INF/rewrite/java-lang-apis.yml
  src/main/resources/META-INF/rewrite/remove-cobertura-maven-plugin.yml
  src/main/resources/META-INF/rewrite/wro4j-maven-plugin.yml
Labels: documentation, enhancement

#349 Upgrade jaxb2-maven-plugin to 2.5.x for Java 9+
  src/main/resources/META-INF/rewrite/java-version-11.yml
Labels: recipe

#244 Remove `Runtime.runFinalizersOnExit()` in upgrade to Java 11
  src/main/java/org/openrewrite/java/migrate/RemoveMethodInvocation.java
  src/main/java/org/openrewrite/java/migrate/jakarta/RemoveMethods.java
  src/main/java/org/openrewrite/java/migrate/lang/RemoveRuntimeTraceMethods.java
  src/main/java/org/openrewrite/java/migrate/lang/RemoveThreadDestroyMethod.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/java-version-8.yml
  src/test/java/org/openrewrite/java/migrate/RemoveMethodInvocationTest.java
  src/test/java/org/openrewrite/java/migrate/lang/RemoveDeprecatedRuntimeTest.java
  src/test/java/org/openrewrite/java/migrate/lang/RemoveThreadDestroyMethodTest.java
Labels: question, recipe

#355 Recipe- BeansXmlNamespace
  src/main/java/org/openrewrite/java/migrate/BeansXmlNamespace.java
  src/test/java/org/openrewrite/java/migrate/BeansXmlNamespaceTest.java
Labels: recipe

#358 Upgrade JAXB maven plugins to Java 17 compatible versions
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: enhancement, recipe

#357 Update maven-compiler-plugin in pluginManagement
  src/main/java/org/openrewrite/java/migrate/UpgradeJavaVersion.java
  src/main/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfiguration.java
  src/test/java/org/openrewrite/java/migrate/jakarta/RemovedUIComponentConstantTest.java
  src/test/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Labels: enhancement
