Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-10, with the labels that each got.

#307 Add recipe descriptors to ApacheCommonsStringUtils
  src/main/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtils.java
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtils.java
  src/main/java/org/openrewrite/java/migrate/lang/StringRules.java
  src/main/java/org/openrewrite/java/migrate/lang/UseStringIsEmpty.java
  src/test/java/org/openrewrite/java/migrate/lang/UseStringIsEmptyTest.java
Labels: documentation

#299 Convert `SequencedCollection.iterator().next()` to `getFirst()`
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/util/SequencedCollectionTest.java
Labels: recipe

#314 Recipe RemovedStateManagerMethods in jakarta-ee-10
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/RemovedStateManagerMethodsTest.java
  src/test/resources/META-INF/rewrite/classpath/jakarta.faces-api-4.0.1.jar
Labels: recipe

#321 Set Maven compiler plugin Java version when using default groupId
  src/main/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfiguration.java
  src/test/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Labels: bug

#322 check if `java.version` exists using MavenResolutionResult
  src/main/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfiguration.java
  src/test/java/org/openrewrite/java/migrate/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Labels: enhancement

#319 Convert Lombok `@Value` classes to Java records
  src/main/java/org/openrewrite/java/migrate/lombok/LombokValueToRecord.java
  src/main/resources/META-INF/rewrite/lombok.yml
  src/test/java/org/openrewrite/java/migrate/lombok/LombokValueToRecordTest.java
Labels: recipe

#323 Adding 4 JakartaEE 10 recipes
  src/main/java/org/openrewrite/java/migrate/jakarta/RemoveMethods.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/FacesJNDINamesChangedTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/RemovedJakartaFacesResourceResolverTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/RemovedUIComponentConstantTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/ServletCookieBehaviorChangeRFC6265Test.java
  src/test/resources/META-INF/rewrite/classpath/jakarta.faces-api-4.0.0-M6.jar
  src/test/resources/META-INF/rewrite/classpath/jakarta.servlet-api-4.0.2.jar
  src/test/resources/META-INF/rewrite/classpath/jakarta.servlet-api-6.0.0.jar
Labels: recipe

#315 `Optional<Stream>.filter(Optional::isPresent).map(Optional::get)` to Java 11 `.flatMap(Optional::stream)`
  src/main/java/org/openrewrite/java/migrate/util/OptionalStreamRecipe.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/util/OptionalStreamRecipeTest.java
Labels: recipe

#334 Polish LombokValueToRecord
  src/main/java/org/openrewrite/java/migrate/lombok/LombokValueToRecord.java
  src/test/java/org/openrewrite/java/migrate/lombok/LombokValueToRecordTest.java
Labels: bug
