Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-08, with the labels that each got.

#266 Migrate `javax.annotation.Nullable` to `jakarta.annotation.Nullable`
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: recipe

#272 Plexus FileUtils refaster template recipes
  build.gradle.kts
  src/main/.gitignore
  src/main/java/org/openrewrite/java/migrate/plexus/PlexusFileUtils.java
  src/test/java/org/openrewrite/java/migrate/plexus/PlexusFileUtilsTest.java
Labels: recipe

#273 Do not partially use text blocks
  src/main/java/org/openrewrite/java/migrate/lang/UseTextBlocks.java
  src/test/java/org/openrewrite/java/migrate/lang/UseTextBlocksTest.java
Labels: bug

#271 Add Apache Commons StringUtils refaster template replacements
  build.gradle.kts
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtils.java
  src/test/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtilsTest.java
Labels: recipe

#276 Fix typos and reformatting for line length.
  README.md
Labels: documentation

#274 Apache Commons File Utils Migrations
  src/main/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtils.java
  src/test/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtilsTest.java
Labels: recipe

#277 Disable some ApacheCommonsStringUtils recipes after seeing results
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtils.java
  src/test/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtilsTest.java
Labels: enhancement

#281 Upgrade `maven-compiler-plugin` to `3.6.2` to support `<release>` tag.
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java
Labels: bug, enhancement, recipe

#283 Only replace repeatable arguments in `StringUtils` recipes
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtils.java
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/IsNotEmptyToJdk.java
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/RepeatableArgumentMatcher.java
  src/test/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtilsTest.java
Labels: bug, enhancement
