Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-09, with the labels that each got.

#278 Added ApacheCommonsFileUtils WriteStringToFile Refaster templates
  src/main/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtils.java
  src/test/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtilsTest.java
Labels: bug, recipe

#293 Rewrite `Stream.collect(Collectors.toUnmodifiableList())` to `Stream.toList()`
  src/main/java/org/openrewrite/java/migrate/util/ReplaceStreamCollectWithToList.java
  src/main/resources/META-INF/rewrite/java-util-apis.yml
  src/test/java/org/openrewrite/java/migrate/util/ReplaceStreamCollectWithToListTest.java
Labels: recipe

#290 `javax.security.cert`, and `com.sun.net.ssl.internal.ssl.Provider` migration recipes
  src/main/java/org/openrewrite/java/migrate/ReplaceStringLiteralValue.java
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java
Labels: recipe

#295 Completes LogRecord.getLongThreadID recipe
  src/main/java/org/openrewrite/java/migrate/ChangeMethodInvocationReturnType.java
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/ChangeMethodInvocationReturnTypeTest.java
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java
Labels: enhancement, recipe

#296 Added jre17AgentMainPreMainPublic recipes
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java
Labels: recipe

#297 Allow migrations to Java 21
  src/main/resources/META-INF/rewrite/java-version-21.yml
Labels: java 20+

#298 Adding WsWsocServerContainerDeprecationRecipe
  .gitignore
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/WsWsocServerContainerDeprecationTest.java
  src/test/resources/META-INF/rewrite/classpath/WsWsocServerContainer_test.jar
Labels: recipe

#300 Added 4 new Java 11 recipes
  src/main/resources/META-INF/rewrite/ibm-java.yml
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeSunJavaToJava11Test.java
  src/test/resources/META-INF/rewrite/classpath/sun.internal.jar
Labels: recipe
