Repository openrewrite/rewrite-migrate-java, pull requests merged in 2023-07, with the labels that each got.

#246 remove thread destroy method recipe
  src/main/java/org/openrewrite/java/migrate/lang/RemoveThreadDestroyMethod.java
  src/test/java/org/openrewrite/java/migrate/lang/RemoveThreadDestroyMethodTest.java
Labels: recipe

#248 Add scope to injected classes
  src/main/java/org/openrewrite/java/migrate/javax/AddScopeToInjectedClass.java
  src/main/java/org/openrewrite/java/migrate/javax/AnnotateTypesVisitor.java
  src/test/java/org/openrewrite/java/migrate/javax/AddScopeToInjectedClassTest.java
Labels: recipe

#259 Add tests to reproduce exceptions in UseVarForGenericsConstructors
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericMethodInvocations.java
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericsConstructors.java
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForObject.java
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForPrimitive.java
  src/test/java/org/openrewrite/java/migrate/lang/UseVarKeywordTest.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericMethodInvocationsTest.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericsConstructorsTest.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForObjectsTest.java
Labels: bug, enhancement, test provided

#263 Fix errors for Arrays and inception bounds
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericMethodInvocations.java
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericsConstructors.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericMethodInvocationsTest.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericsConstructorsTest.java
Labels: bug

#264 fix: added emptyList for annotations akin to the adaption made to cor…
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericMethodInvocations.java
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForGenericsConstructors.java
Labels: bug

#265 Upgrade Lombok for Java 11
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/lombok.yml
  src/test/java/org/openrewrite/java/migrate/lombok/UpdateLombokToJava11Test.java
Labels: enhancement

#245 Remove inputstream finalizer
  src/main/java/org/openrewrite/java/migrate/io/ReplaceFileInOrOutputStreamFinalizeWithClose.java
  src/main/java/org/openrewrite/java/migrate/io/package-info.java
  src/test/java/org/openrewrite/java/migrate/io/ReplaceFileInOrOutputStreamFinalizeWithCloseTest.java
Labels: recipe
