Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-10, with the labels that each got.

#570 `UseEnumSetOf` should rewrite `EnumSet.noneOf` from empty `Set.of()`
  src/main/java/org/openrewrite/java/migrate/util/UseEnumSetOf.java
  src/test/java/org/openrewrite/java/migrate/util/UseEnumSetOfTest.java
Labels: bug, enhancement

#572 Migrate Spring annotations to JSpecify
  build.gradle.kts
  src/main/resources/META-INF/rewrite/jspecify.yml
  src/test/java/org/openrewrite/java/migrate/jspecify/MigrateToJspecifyTest.java
Labels: recipe

#575 `Preconditions.checkNotNull` recipes should retain unrelated `String.valueOf(String)`
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaRefaster.java
Labels: enhancement

#579 Add recipe to upgrade `jakarta.annotation-api` to 2.1.x version
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
Labels: enhancement

#582 [2/x] Implement joda to java time migration recipe
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeFlowSpec.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeScanner.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeVisitor.java
  src/main/java/org/openrewrite/java/migrate/joda/SafeCheckMarker.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AbstractInstantTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/TimeClassMap.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/TimeClassNames.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeFlowSpecTest.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeScannerTest.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeVisitorTest.java
Labels: recipe

#594 Joda time to Java time: Add few more templates for migration
  build.gradle.kts
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeVisitor.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AbstractDateTimeTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AbstractDurationTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AbstractInstantTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AllTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/BaseDateTime.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DateTimeFormatTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DateTimeFormatterTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DateTimeTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DurationTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/InstantTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/Templates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/TimeClassNames.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/TimeZoneTemplates.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeVisitorTest.java
Labels: recipe
