Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-07, with the labels that each got.

#505 Add JavaxOrmXmlToJakartaOrmXml as suggested in Slack
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: recipe

#503 Remove `Thread.destroy()` and `Thread.stop(Throwable)`
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ThreadStopDestroyTest.java
Labels: recipe

#507 Fixed version Typo in JavaxWsToJakartaWs Recipe
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: bug

#510 Replace `Reference.clone()` with new constructor in Java 11 migration
  src/main/java/org/openrewrite/java/migrate/ReferenceCloneMethod.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ReferenceCloneMethodTest.java
Labels: recipe

#508 Replace com.sun.xml.internal.bind.* packages with com.sun.xml.bind.* packages
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/InternalBindPackagesTest.java
  src/test/resources/META-INF/rewrite/classpath/sun.internal.newClass.jar
Labels: recipe

#513 Added support for javax.inject
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxInjectToJakartaInjectTest.java
Labels: enhancement, recipe

#515 Recipe descriptions should consistently end in a dot
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/main/resources/META-INF/rewrite/jakarta-faces-4.yml
  src/main/resources/META-INF/rewrite/java-concurrent-apis.yml
  src/main/resources/META-INF/rewrite/java-ee-8.yml
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
Labels: bug, documentation

#518 fix: UseEnumSetOf should ignore array and varargs parameters
  src/main/java/org/openrewrite/java/migrate/util/UseEnumSetOf.java
  src/test/java/org/openrewrite/java/migrate/util/UseEnumSetOfTest.java
Labels: bug

#517 Adding all org.glassfish.main migrations to jakarta
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: enhancement, recipe

#519 Replace `Paths.get` with `Path.of`
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/nio/file/PathsGetToPathOfTest.java
Labels: recipe

#521 ChangeMethodInvocationReturnType should shorten FQCN
  src/main/java/org/openrewrite/java/migrate/ChangeMethodInvocationReturnType.java
  src/test/java/org/openrewrite/java/migrate/ChangeMethodInvocationReturnTypeTest.java
Labels: enhancement
