Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-08, with the labels that each got.

#522 Add Refaster style recipes for Guava
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaRefaster.java
  src/main/resources/META-INF/rewrite/no-guava.yml
  src/test/java/org/openrewrite/java/migrate/guava/PreferJavaUtilObjectsTest.java
Labels: recipe

#525 Fix #457: Refactor javax.annotation to ChangePackage
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: enhancement

#524 Recipe ReplaceAWTGetPeerMethod in Java 11 Migration
  src/main/java/org/openrewrite/java/migrate/ReplaceAWTGetPeerMethod.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ReplaceAWTGetPeerMethodTest.java
Labels: recipe

#529 Upgrade Scala dependencies as part of Java 11 upgrade
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/scala.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeScalaTest.java
Labels: recipe

#530 Add Recipe RemovedRuntimeTraceMethods Java 17
  src/main/resources/META-INF/rewrite/java-version-17.yml
Labels: recipe

#533 Use a transient field for `seen` in FindJavaVersion
  src/main/java/org/openrewrite/java/migrate/search/FindJavaVersion.java
  src/test/java/org/openrewrite/java/migrate/search/FindJavaVersionTest.java
Labels: bug

#538 Handle generics in PreferJavaUtilObjectsRequireNonNull
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaRefaster.java
  src/main/resources/META-INF/rewrite/no-guava.yml
  src/test/java/org/openrewrite/java/migrate/guava/PreferJavaUtilObjectsTest.java
Labels: enhancement, recipe

#532 Recipe ReplaceLocalizedStreamMethods
  src/main/java/org/openrewrite/java/migrate/ReplaceLocalizedStreamMethods.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ReplaceLocalizedStreamMethodsTest.java
Labels: recipe

#541 Recipes to migrate from Javax, Jakarta and JetBrains nullability annotations to JSpecify
  build.gradle.kts
  src/main/resources/META-INF/rewrite/jspecify.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java
  src/test/java/org/openrewrite/java/migrate/jspecify/MigrateToJspecifyTest.java
Labels: recipe
