Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-02, with the labels that each got.

#401 Fully remove part provider and last remaining references
  src/main/java/org/openrewrite/java/migrate/util/MigrateCollectionsSingletonList.java
  src/test/java/org/openrewrite/java/migrate/util/MigrateCollectionsSingletonListTest.java
Labels: enhancement

#402 Automatically review PRs
  .github/workflows/comment-pr.yml
  .github/workflows/receive-pr.yml
Labels: enhancement

#392 Add recipe for rule: HttpSessionInvalidate
  src/main/java/org/openrewrite/java/migrate/javax/HttpSessionInvalidate.java
  src/main/resources/META-INF/rewrite/classpath/javax.servlet-3.0.jar
  src/main/resources/META-INF/rewrite/java-ee-6.yml
  src/main/resources/META-INF/rewrite/java-ee-7.yml
  src/test/java/org/openrewrite/java/migrate/javaee/HttpSessionInvalidateTest.java
Labels: recipe

#405 AutoGeneratedValue recipe
  src/main/java/org/openrewrite/java/migrate/javax/AddTableGenerator.java
  src/main/resources/META-INF/rewrite/java-ee-7.yml
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javaee/AddTableGeneratorTest.java
  src/test/resources/META-INF/rewrite/classpath/javax.persistence-api-2.2.jar
Labels: recipe

#414 Improve the wording of a few recipe description
  src/main/java/org/openrewrite/java/migrate/apache/commons/io/ApacheCommonsFileUtils.java
  src/main/java/org/openrewrite/java/migrate/apache/commons/lang/ApacheCommonsStringUtils.java
  src/main/java/org/openrewrite/java/migrate/maven/shared/MavenSharedStringUtils.java
  src/main/java/org/openrewrite/java/migrate/plexus/PlexusFileUtils.java
  src/main/java/org/openrewrite/java/migrate/plexus/PlexusStringUtils.java
Labels: documentation

#418 ClassCastException in OptionalNotEmptyToIsPresent
  src/main/java/org/openrewrite/java/migrate/util/OptionalNotEmptyToIsPresent.java
  src/main/java/org/openrewrite/java/migrate/util/OptionalNotPresentToIsEmpty.java
  src/test/java/org/openrewrite/java/migrate/util/OptionalNotEmptyToIsPresentTest.java
Labels: bug

#424 Expand ListFirstAndLast covered cases to include `getList().get(0)`
  src/main/java/org/openrewrite/java/migrate/util/ListFirstAndLast.java
  src/test/java/org/openrewrite/java/migrate/util/ListFirstAndLastTest.java
Labels: bug
