Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-04, with the labels that each got.

#431 Add recipe to prefer java standard library over guava `Maps.newHashMa…
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaMapsNewHashMap.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaMapsNewHashMapTest.java
Labels: recipe

#413 Recipe to remove Id annotation from Embeddable class when referenced by EmbeddedId
  src/main/java/org/openrewrite/java/migrate/javax/RemoveEmbeddableId.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/RemoveEmbeddableIdTest.java
Labels: recipe

#410 Add @Column along @ElementCollection for OpenJPA to EclipseLink migration
  src/main/java/org/openrewrite/java/migrate/javax/AddColumnAnnotation.java
  src/main/resources/META-INF/rewrite/classpath/javax.persistence-api-2.2.jar
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddColumnAnnotationTest.java
Labels: recipe

#443 Upgrade ModelMapper dependency to support Java 21
  src/main/resources/META-INF/rewrite/java-version-21.yml
Labels: recipe, java 21+

#415 Add default constructor to Entity class
  src/main/java/org/openrewrite/java/migrate/javax/AddDefaultConstructorToEntityClass.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddDefaultConstructorToEntityClassTest.java
Labels: recipe

#460 Add missing method impl interface
  src/main/java/org/openrewrite/java/migrate/AddMissingMethodImplementation.java
  src/test/java/org/openrewrite/java/migrate/AddMissingMethodImplementationTest.java
Labels: bug

#463 fix: Add Jakarta XML WS API when using javax.xml.ws
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddJaxwsDependenciesTest.java
Labels: bug, enhancement

#444 Jakarta EE Upgrade Recipe Cleanup
  src/main/java/org/openrewrite/java/migrate/jakarta/MaybeAddJakartaServletApi.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/MaybeAddJakartaServletApiTest.java
Labels: bug

#416 Use JoinColumn annotation for relationship mappings
  src/main/java/org/openrewrite/java/migrate/javax/UseJoinColumnForMapping.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/UseJoinColumnForMappingTest.java
Labels: recipe

#452 Improve handling of interfaces in LombokValueToRecord
  src/main/java/org/openrewrite/java/migrate/lombok/LombokValueToRecord.java
  src/test/java/org/openrewrite/java/migrate/lombok/LombokValueToRecordTest.java
Labels: enhancement

#437 Recipe to remove `Thread.countStackFrames()`.
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/DeprecatedCountStackFramesMethodTest.java
Labels: recipe

#420 Remove Temporal annotation from attributes to avoid EclipseLink error
  src/main/java/org/openrewrite/java/migrate/javax/RemoveTemporalAnnotation.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/RemoveTemporalAnnotationTest.java
Labels: recipe

#421 Add Transient annotation to Collections without JPA annotations
  src/main/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToCollections.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToCollectionsTest.java
Labels: recipe

#422 Add Transient annotation to Entity without JPA annotation
  src/main/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToEntity.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToEntityTest.java
Labels: recipe
