Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-09, with the labels that each got.

#543 Recipe to migrate from `Math.random` to `ThreadLocalRandom`
  src/main/java/org/openrewrite/java/migrate/util/ReplaceMathRandomWithThreadLocalRandom.java
  src/main/resources/META-INF/rewrite/java-version-7.yml
  src/test/java/org/openrewrite/java/migrate/util/ReplaceMathRandomWithThreadLocalRandomRecipeTest.java
Labels: recipe

#548 Remove parameters from java-version-11.yml for DetectAWTGetPeerMethod recipe
  src/main/java/org/openrewrite/java/migrate/ReplaceAWTGetPeerMethod.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
Labels: enhancement

#552 Skip adding var to local variables initialized by array initializer
  src/main/java/org/openrewrite/java/migrate/lang/var/UseVarForObject.java
  src/test/java/org/openrewrite/java/migrate/lang/var/UseVarForObjectsTest.java
Labels: bug

#556 StringFormatted should not leave trailing whitespace after replacement
  src/main/java/org/openrewrite/java/migrate/lang/StringFormatted.java
  src/test/java/org/openrewrite/java/migrate/lang/StringFormattedTest.java
Labels: bug

#557 fix: Handle ImmutableOf as Select on MethodInvocation
  src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableListOfTest.java
Labels: bug

#558 Drop unnecessary trailing escape in UseTextBlocks
  src/main/java/org/openrewrite/java/migrate/lang/UseTextBlocks.java
  src/test/java/org/openrewrite/java/migrate/lang/UseTextBlocksTest.java
Labels: bug, enhancement

#549 Correctly override parent property to set Java version
  src/main/java/org/openrewrite/java/migrate/maven/UpdateMavenProjectPropertyJavaVersion.java
  src/test/java/org/openrewrite/java/migrate/maven/UpdateMavenProjectPropertyJavaVersionTest.java
Labels: bug

#560 Java 17 recipe add serialVersionUUID and @Serial by default
  src/main/resources/META-INF/rewrite/java-version-17.yml
Labels: enhancement
