Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-01, with the labels that each got.

#383 Add useMimeCoder option to UseJavaUtilBase64
  src/main/java/org/openrewrite/java/migrate/UseJavaUtilBase64.java
  src/test/java/org/openrewrite/java/migrate/UseJavaUtilBase64Test.java
Labels: enhancement

#398 Minor polish related to Java 17 and 21 bumps
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava17Test.java
Labels: enhancement

#403 Use `getFirst()` instead of `stream().findFirst().orElseThrow()`
  src/main/java/org/openrewrite/java/migrate/util/IteratorNext.java
  src/main/java/org/openrewrite/java/migrate/util/ListFirstAndLast.java
  src/main/java/org/openrewrite/java/migrate/util/StreamFindFirst.java
  src/test/java/org/openrewrite/java/migrate/util/IteratorNextTest.java
  src/test/java/org/openrewrite/java/migrate/util/ListFirstAndLastTest.java
  src/test/java/org/openrewrite/java/migrate/util/StreamFindFirstTest.java
Labels: bug, recipe

#404 Remove illegal semicolons in Java 21
  src/main/java/org/openrewrite/java/migrate/RemoveIllegalSemicolons.java
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/RemoveIllegalSemicolonsTest.java
Labels: recipe

#340 CDI recipe
  src/main/java/org/openrewrite/java/migrate/jakarta/RemoveBeanIsNullable.java
  src/main/java/org/openrewrite/java/migrate/jakarta/UpdateAddAnnotatedTypes.java
  src/main/java/org/openrewrite/java/migrate/jakarta/UpdateBeanManagerMethods.java
  src/main/resources/META-INF/rewrite/classpath/jakarta.enterprise.cdi-api-3.0.0-M4.jar
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/RemoveBeanIsNullableTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateAddAnnotatedTypesTest.java
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateBeanManagerMethodsTest.java
Labels: recipe

#338 RemovalsServletJakarta10 Recipe
  src/main/java/org/openrewrite/java/migrate/jakarta/UpdateGetRealPath.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/RemovalsServletJakarta10Test.java
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateGetRealPathTest.java
  src/test/resources/META-INF/rewrite/classpath/jakarta.servlet-api-5.0.0.jar
  src/test/resources/META-INF/rewrite/classpath/javax.servlet-api-4.0.0.jar
Labels: recipe
