Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-05, with the labels that each got.

#468 Drop intermediate JavaVersion11/17/21 recipes
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/UpdateMavenToJava11Test.java
  src/test/java/org/openrewrite/java/migrate/UpgradeJavaVersionTest.java
Labels: enhancement

#470 allow @Builder annotation in LombokValueToBuilder
  src/main/java/org/openrewrite/java/migrate/lombok/LombokValueToRecord.java
  src/test/java/org/openrewrite/java/migrate/lombok/LombokValueToRecordTest.java
Labels: enhancement

#471 jacoco upgrade now includes arbitrary jacoco deps (eg agent), always …
  src/main/resources/META-INF/rewrite/jacoco.yml
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/main/resources/META-INF/rewrite/java-version-6.yml
  src/test/java/org/openrewrite/java/migrate/UpgradeToJava6Test.java
  src/test/java/org/openrewrite/java/migrate/jacoco/UpgradeJaCoCoMavenPluginVersionTest.java
  src/test/java/org/openrewrite/java/migrate/jacoco/UpgradeJaCoCoTest.java
Labels: enhancement, recipe

#473 Also change Guava Predicate method name
  src/main/resources/META-INF/rewrite/no-guava.yml
  src/test/java/org/openrewrite/java/migrate/guava/PreferJavaUtilPredicateTest.java
Labels: bug

#425 Add Transient annotation to private accessor methods
  src/main/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToPrivateAccessor.java
  src/main/resources/META-INF/rewrite/openjpa-to-eclipselink.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddTransientAnnotationToPrivateAccessorTest.java
Labels: recipe

#479 Fix #478: EE bean validation.properties and SPI
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: recipe

#476 recipes for build and plugin upgrade
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/java-version-21.yml
Labels: recipe

#477 Recipe to call ToolProvider methods as static methods, not on instances
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/test/java/org/openrewrite/java/migrate/RemovedToolProviderConstructorTest.java
Labels: recipe
