Repository openrewrite/rewrite-migrate-java, pull requests merged in 2024-11, with the labels that each got.

#595 Use Java 21 toolchain for rewrite-migrate-java
  .sdkmanrc
  build.gradle.kts
  src/test/java/org/openrewrite/java/migrate/DeleteDeprecatedFinalizeTest.java
  src/test/java/org/openrewrite/java/migrate/util/SequencedCollectionTest.java
Labels: java 21+

#599 Retain BeanManager `fireEvent` annotations
  src/main/java/org/openrewrite/java/migrate/jakarta/UpdateBeanManagerMethods.java
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateBeanManagerMethodsTest.java
Labels: bug

#600 Jspecify nullmarked
  src/main/resources/META-INF/rewrite/jspecify.yml
  src/test/java/org/openrewrite/java/migrate/jspecify/MigrateToJspecifyTest.java
Labels: enhancement

#603 Proof that `javax.jms` is migrated to `jakarta.jms` in spring.xml
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxToJakartaTest.java
Labels: enhancement

#606 Adopt RemoveMethodInvocations from core
  src/main/java/org/openrewrite/java/migrate/RemoveMethodInvocation.java
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/java-version-17.yml
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/main/resources/META-INF/rewrite/java-version-8.yml
  src/test/java/org/openrewrite/java/migrate/RemoveMethodInvocationTest.java
Labels: enhancement

#610 Add `lombok-mapstruct-binding` during Java 17 migration when both lombok and mapstruct are used
  src/main/java/org/openrewrite/java/migrate/lang/MigrateSecurityManagerMulticast.java
  src/main/resources/META-INF/rewrite/java-version-17.yml
Labels: enhancement, recipe

#613 Replace `ArrayStoreException` with `TypeNotPresentException` in try/catch using `Class.getAnnotation()`
  src/main/java/org/openrewrite/java/migrate/ArrayStoreExceptionToTypeNotPresentException.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ArrayStoreExceptionToTypeNotPresentExceptionTest.java
Labels: recipe

#605 Joda-Time to Java time: Add support for Method Parameter Migration
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeFlowSpec.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeRecipe.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeScanner.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeVisitor.java
  src/main/java/org/openrewrite/java/migrate/joda/ScopeAwareVisitor.java
  src/main/java/org/openrewrite/java/migrate/joda/package-info.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AbstractDurationTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/AllTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DateTimeTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/DurationTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/TimeClassMap.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/VarTemplates.java
  src/main/java/org/openrewrite/java/migrate/joda/templates/package-info.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeFlowSpecTest.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeRecipeTest.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeScannerTest.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeVisitorTest.java
Labels: recipe

#601 Do not convert return types in NoGuavaJava21 by default
  src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableListOf.java
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableMapOf.java
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableSetOf.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableListOfTest.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableMapOfTest.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaImmutableSetOfTest.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaJava21Test.java
Labels: bug
