Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-08, with the labels that each got.

#809 The quick fix for the tests for Jaxws Dependencies
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/UpdateSdkManTest.java
  src/test/java/org/openrewrite/java/migrate/javax/AddJaxwsDependenciesTest.java
Labels: bug, test provided

#813 Create `is` methods for boolean fields in `LombokValueToRecord`
  src/main/java/org/openrewrite/java/migrate/lombok/LombokValueToRecord.java
  src/test/java/org/openrewrite/java/migrate/lombok/LombokValueToRecordTest.java
Labels: enhancement, lombok

#811 Joda-time: Make safe migration optional
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeRecipe.java
  src/main/java/org/openrewrite/java/migrate/joda/JodaTimeScanner.java
  src/test/java/org/openrewrite/java/migrate/joda/JodaTimeRecipeTest.java
Labels: enhancement

#832 Fix recipe reference to `AccessController` migration for Java 25
  src/main/resources/META-INF/rewrite/java-version-25.yml
Labels: bug, recipe

#838 AddJaxbRuntime should use `overrideManagedDependency=true`
  src/main/java/org/openrewrite/java/migrate/javax/AddJaxbRuntime.java
Labels: enhancement
