Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-05, with the labels that each got.

#713 Security Manager API Removal
  src/main/resources/META-INF/rewrite/java-version-25.yml
Labels: recipe

#717 UseImportPolicy in NoGuavaRefaster
  src/main/java/org/openrewrite/java/migrate/guava/NoGuavaRefaster.java
  src/main/resources/META-INF/rewrite/examples.yml
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaRefasterTest.java
Labels: enhancement

#719 Migrate `com:intellij:annotations` to `org.jetbrains:annotations`
  src/main/resources/META-INF/rewrite/examples.yml
  src/main/resources/META-INF/rewrite/intellij-annotations-to-jetbrains-annotations.yml
  src/test/java/org/openrewrite/java/migrate/ComIntelliJAnnotationsToOrgJetbrainsAnnotationsTest.java
Labels: good first issue, recipe

#729 Upgrade existing jakarta.annotation-api to 2.0.x for EE9
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JavaxToJakartaTest.java
Labels: enhancement

#732 Recursive package change last in jakarta-ee-9.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: bug

#739 Add Java 21 migration to Java 25
  src/main/resources/META-INF/rewrite/java-version-25.yml
Labels: java 25+

#744 Add JSpecify best practices recipe
  src/main/resources/META-INF/rewrite/jspecify.yml
  src/test/java/org/openrewrite/java/migrate/jspecify/JSpecifyBestPracticesTest.java
Labels: recipe

#727 New recipe to only add JAXB API dependencies without runtime dependencies
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/main/resources/META-INF/rewrite/jaxb-apis.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddJaxbDependenciesWithRuntimeTest.java
  src/test/java/org/openrewrite/java/migrate/javax/AddJaxbDependenciesWithoutRuntimeTest.java
Labels: recipe
