Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-01, with the labels that each got.

#651 Prefer JDK methods for Maps and Sets of an expected size
  build.gradle.kts
  src/main/java/org/openrewrite/java/migrate/guava/NoMapsAndSetsWithExpectedSize.java
  src/main/resources/META-INF/rewrite/no-guava.yml
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaJava21Test.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaRefasterTest.java
  src/test/java/org/openrewrite/java/migrate/guava/NoGuavaTest.java
  src/test/java/org/openrewrite/java/migrate/guava/NoMapsAndSetsWithExpectedSizeTest.java
Labels: enhancement, recipe

#644 feat: use Lombok Log Annotations
  build.gradle.kts
  src/main/java/org/openrewrite/java/migrate/lombok/log/LogVisitor.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseCommonsLog.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseJBossLog.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseLog.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseLog4j2.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseLogRecipeTemplate.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/UseSlf4j.java
  src/main/java/org/openrewrite/java/migrate/lombok/log/package-info.java
  src/main/resources/META-INF/rewrite/lombok.yml
  src/test/java/org/openrewrite/java/migrate/lombok/log/ConvertAnyLogTest.java
  src/test/java/org/openrewrite/java/migrate/lombok/log/ConvertToLogAnnotationTest.java
Labels: recipe

#645 feat: use lombok @NoArgsConstructor annotation
  src/main/java/org/openrewrite/java/migrate/lombok/UseNoArgsConstructor.java
  src/test/java/org/openrewrite/java/migrate/lombok/UseNoArgsConstructorTest.java
Labels: recipe

#656 Add migration from `javax.servlet.servlet-api` to `javax.servlet.javax.servlet-api`
  src/main/resources/META-INF/rewrite/java-ee-8.yml
Labels: enhancement
