Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-06, with the labels that each got.

#754 Pick better SDKMan versions
  src/main/java/org/openrewrite/java/migrate/UpdateSdkMan.java
  src/test/java/org/openrewrite/java/migrate/UpdateSdkManTest.java
Labels: bug, test provided

#722 Recipes for searching Threads or Executors usage
  src/main/resources/META-INF/rewrite/java-virtual-threads.yml
  src/test/java/org/openrewrite/java/migrate/lang/UseThreadsOrExecutorsTest.java
Labels: recipe

#755 Make fields annotated with `@Produces` static
  src/main/java/org/openrewrite/java/migrate/AddStaticVariableOnProducerSessionBean.java
  src/main/resources/META-INF/rewrite/java-ee-7.yml
  src/test/java/org/openrewrite/java/migrate/AddStaticVariableOnProducerSessionBeanTest.java
Labels: recipe

#762 Add only declarable Gradle jax-ws runtime dependencies
  src/main/java/org/openrewrite/java/migrate/javax/AddJaxwsRuntime.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/javax/AddJaxwsDependenciesTest.java
Labels: bug, recipe

#771 Fix for `UpdateSdkMan` allowing downgrade of Java version
  src/main/java/org/openrewrite/java/migrate/UpdateSdkMan.java
  src/test/java/org/openrewrite/java/migrate/UpdateSdkManTest.java
Labels: bug, test provided

#774 Improved the support of types
  src/main/java/org/openrewrite/java/migrate/lang/IfElseIfConstructToSwitch.java
  src/test/java/org/openrewrite/java/migrate/lang/IfElseIfConstructToSwitchTest.java
Labels: bug

#775 Some compilation issues are occuring after running switch pattern matching recipe
  src/main/java/org/openrewrite/java/migrate/lang/IfElseIfConstructToSwitch.java
  src/main/java/org/openrewrite/java/migrate/lang/NullCheckAsSwitchCase.java
  src/test/java/org/openrewrite/java/migrate/lang/IfElseIfConstructToSwitchTest.java
  src/test/java/org/openrewrite/java/migrate/lang/NullCheckAsSwitchCaseTest.java
  src/test/java/org/openrewrite/java/migrate/util/MigrateCollectionsSingletonMapTest.java
Labels: bug
