Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-02, with the labels that each got.

#667 Java 11 recipe for default keystore change
  src/main/java/org/openrewrite/java/migrate/ChangeDefaultKeyStore.java
  src/main/resources/META-INF/rewrite/java-version-11.yml
  src/test/java/org/openrewrite/java/migrate/ChangeDefaultKeyStoreTest.java
Labels: recipe

#670 Polish ChangeDefaultKeyStore to only apply to Java 11
  src/main/java/org/openrewrite/java/migrate/ChangeDefaultKeyStore.java
  src/test/java/org/openrewrite/java/migrate/ChangeDefaultKeyStoreTest.java
Labels: bug

#672 Omit migration to @Setter annotated field of other annotations are present
  src/main/java/org/openrewrite/java/migrate/lombok/LombokUtils.java
  src/main/java/org/openrewrite/java/migrate/lombok/UseLombokGetter.java
  src/main/java/org/openrewrite/java/migrate/lombok/UseLombokSetter.java
  src/test/java/org/openrewrite/java/migrate/lombok/UseLombokGetterTest.java
  src/test/java/org/openrewrite/java/migrate/lombok/UseLombokSetterTest.java
Labels: bug

#674 Align JakartaEE migrations with EE9 vs EE10 versions
  src/main/resources/META-INF/rewrite/jakarta-ee-10.yml
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/main/resources/META-INF/rewrite/jakarta-faces-4.yml
Labels: bug, enhancement

#675 Adopt type tables
  build.gradle.kts
  src/main/resources/META-INF/rewrite/classpath.tsv.zip
  src/main/resources/META-INF/rewrite/classpath/jakarta.enterprise.cdi-api-3.0.0-M4.jar
  src/main/resources/META-INF/rewrite/classpath/javax.persistence-api-2.2.jar
  src/main/resources/META-INF/rewrite/classpath/javax.servlet-3.0.jar
Labels: enhancement

#678 Improve Handling of Absolute, Relative, and Non-Literal URLs in URL Migration
  src/main/java/org/openrewrite/java/migrate/net/URLConstructorsToURI.java
  src/main/resources/META-INF/rewrite/java-version-21.yml
  src/test/java/org/openrewrite/java/migrate/net/URLConstructorsToURITest.java
Labels: recipe
