Repository openrewrite/rewrite-migrate-java, pull requests merged in 2025-04, with the labels that each got.

#693 Fix #692: Replace "java.faces" in Java file strings
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
Labels: enhancement, recipe

#704 Migrate XJC bindings to Jakarta EE
  src/main/resources/META-INF/rewrite/jakarta-ee-9.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/UpdateXJCBindingsToJakartaEE.java
Labels: enhancement

#703 Jakarta EE11 / Faces 4.1
  src/main/resources/META-INF/rewrite/jakarta-ee-11.yml
  src/main/resources/META-INF/rewrite/jakarta-faces-41.yml
  src/test/java/org/openrewrite/java/migrate/jakarta/JakartaEE11Test.java
Labels: recipe

#631 feat: normalize effective getter methods
  src/main/java/org/openrewrite/java/migrate/lombok/AdoptLombokGetterMethodNames.java
  src/main/java/org/openrewrite/java/migrate/lombok/LombokUtils.java
  src/test/java/org/openrewrite/java/migrate/lombok/AdoptLombokGetterMethodNamesTest.java
Labels: recipe, lombok
